[en]
  title = "New World | YoungWilliam"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[zh]
 languageCode = "zh-Hans"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/zh"
