language: node_js # 设置语言
node_js: stable # 设置相应版本

env:
    global:
        - GH_REF: github.com/YoungWilliamZ/YoungWilliamZ.github.io.git

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

branches:
 only:
   - hexo

before install:

  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  # - sed -i "s/gh_token/${GITHUB_TOKEN}/g" ./_config.yml
  # - sed -i "s/gitment_id_token/${Gitment_Client_ID}/g" ./themes/next/_config.yml
  # - sed -i "s/gitment_secret_token/${Gitment_Client_Secret}/g" ./themes/next/_config.yml
  # - npm install -g hexo

  # - npm install hexo-deployer-git --save

# S: Build Lifecycle
install:
  - npm install -g hexo-cli 
  - npm install hexo-generator-searchdb --save
  - npm install hexo-generator-feed --save
  - npm install

# before_script:


script:
  - hexo clean
  - hexo g

after_script:
  # - git clone https://${GH_REF} .deploy_git
  # - cd .deploy_git
  # - git checkout master
  # - cd ../
  # - mv .deploy_git/.git/ ./public/
  # - cd ./public
  - git config user.name "YoungWilliam"
  - git config user.email "youngwilliam.zheng@gmail.com"
  # - git add .
  # - git commit -m "Travis CI Auto Builder"
  # - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master
  - npm install hexo-deployer-git --save
  - sed -i "s/gh_token/${GITHUB_TOKEN}/g" ./_config.yml
  - hexo deploy
# E: Build LifeCycle
